export interface CareerJobSection {
  heading?: string;
  paragraphs?: string[];
  items?: string[];
  outro?: string[];
}

export interface CareerJob {
  slug: string;
  title: string;
  excerpt: string;
  /** Badge shown on the listing card and detail-page eyebrow. Defaults to "Open Position" when omitted. */
  badgeLabel?: string;
  /** Apply button text. Defaults to "Apply for This Role" when omitted. */
  applyLabel?: string;
  metaTitle: string;
  metaDescription: string;
  intro: string[];
  sections: CareerJobSection[];
  closing: string[];
  questions: string[];
}

export const careersData: CareerJob[] = [
  {
    slug: "founding-operator-entrepreneur-in-residence-verclara",
    title: "Founding Operator / Entrepreneur-in-Residence — Verclara",
    excerpt:
      "Take ownership of Verclara's commercial growth as a Founding Operator. Not a traditional salaried role — compensation is structured around equity, profit share, and a path to leading the business.",
    metaTitle: "Careers — Founding Operator / Entrepreneur-in-Residence | Audax Ventures",
    metaDescription:
      "Audax Ventures is looking for a Founding Operator / EIR to take ownership of Verclara's growth, with compensation tied to equity and profits.",
    intro: [
      "Want to build a software company, but haven't found the right idea yet?",
      "We may have an opportunity for you.",
      "At Audax Ventures, we've built and launched Verclara (www.verclara.io), a CRM and business operating system designed specifically for service-based businesses, consultants, fractional executives and small teams.",
      "The product is built. The technology is in place. The brand is launched.",
      "Now we're looking for the right entrepreneur to help turn Verclara into a growing SaaS company. We're looking for a Founding Operator / Entrepreneur-in-Residence who wants to take ownership of Verclara's growth and eventually have the opportunity to lead the business.",
      "This is not a traditional salaried position. It's an opportunity for someone who wants to become an entrepreneur and build meaningful ownership in a company without having to start from a blank page.",
    ],
    sections: [
      {
        heading: "What You'll Own",
        paragraphs: ["You'll take the lead on the commercial growth of Verclara, including:"],
        items: [
          "Customer acquisition and sales",
          "Marketing and go-to-market strategy",
          "Partnerships and distribution",
          "Customer onboarding and retention",
          "Gathering customer feedback and helping shape the product roadmap",
          "Testing new growth channels and opportunities",
          "Building the processes required to scale the business",
        ],
        outro: [
          "You won't be doing it alone. Audax will continue to provide the software development, technical infrastructure and strategic support behind the platform.",
        ],
      },
      {
        heading: "The Opportunity",
        paragraphs: [
          "There is no traditional salary at the outset. Instead, we want the person running Verclara to think and operate like an owner.",
          "The compensation structure will include:",
        ],
        items: [
          "Meaningful equity in Verclara that vests over time",
          "Additional equity tied to achieving major growth milestones",
          "A percentage of monthly profits generated by Verclara",
          "A pathway toward salaried compensation as the business reaches defined revenue milestones",
          "The opportunity to ultimately become the long-term leader of Verclara",
        ],
        outro: ["The better Verclara performs, the more valuable this opportunity becomes for you."],
      },
      {
        heading: "Who We're Looking For",
        paragraphs: ["You might be a great fit if you:"],
        items: [
          "Have always wanted to build a company of your own",
          "Are excited by startups, SaaS and entrepreneurship",
          "Are comfortable selling and talking to customers",
          "Can operate independently without waiting for someone to tell you what to do",
          "Are willing to experiment, fail quickly and keep moving",
          "Care more about ownership and long-term upside than having a conventional job",
          "Want to take something that already exists and make it significantly bigger",
        ],
        outro: [
          "You do not need to have founded a company before. We care much more about your drive, commercial instincts, creativity and ability to execute than the number of years on your resume.",
          "If your goal is simply to find another job, this probably isn't the right opportunity.",
          "But if you've been waiting for the right opportunity to become an entrepreneur, this might be it.",
        ],
      },
    ],
    closing: [
      "Interested? Apply today and include a cover letter that tells us a little about yourself, why entrepreneurship interests you, and what you would do in your first 90 days to grow Verclara.",
      "We want to find someone with strong entrepreneurial mindset qualities that is ready to work hard and build an innovative SaaS company.",
      "Bonus points if you submit a video of yourself talking as your cover letter!",
    ],
    questions: [
      "Do you have any previous entrepreneurship experience? (don't worry, this isn't a requirement!)",
      "Are you willing and/or able to invest any money into the company? (don't worry, this isn't a requirement!)",
      "Do you understand and accept that this opportunity does not include a guaranteed salary at the outset, with compensation instead structured around equity ownership and a share of profits?",
      "Are you looking for an entrepreneurial opportunity where your compensation and long-term upside are directly tied to the growth and performance of the business?",
      "Are you comfortable taking primary ownership of Verclara's sales, marketing, customer acquisition and overall business growth?",
    ],
  },
  {
    slug: "audax-founder-program",
    title: "Audax Founder Program",
    excerpt:
      "A selective venture-building program for aspiring entrepreneurs. No startup idea required — just the ambition to build one, with Audax's technology and product team behind you.",
    badgeLabel: "Open Program",
    applyLabel: "Apply to the Program",
    metaTitle: "Careers — Audax Founder Program | Audax Ventures",
    metaDescription:
      "The Audax Founder Program is a selective venture-building program for aspiring entrepreneurs who want to build a technology company with Audax's team.",
    intro: [
      "You don't need a startup idea. You need the ambition to build one.",
      "Have you always wanted to become an entrepreneur and build a technology company, but something has been holding you back?",
      "Maybe you have an idea but don't know how to build the technology. Maybe you've identified an industry or problem you want to pursue but haven't figured out the right business model. Or maybe you simply know you want to become an entrepreneur but haven't found the right idea yet.",
      "That's exactly what the Audax Founder Program is designed for.",
      "The Audax Founder Program is a selective venture-building program for aspiring entrepreneurs who want to build a software, AI or technology-enabled company with the resources and support of an experienced technology team behind them.",
      "You bring the ambition, commitment and willingness to build. We'll help with the rest.",
    ],
    sections: [
      {
        heading: "Starting Without an Idea? That's Okay.",
        paragraphs: [
          "For selected founders who haven't identified their business idea yet, we'll work together to explore potential opportunities based on your experience, interests, network and areas of expertise. We'll look for real problems worth solving, evaluate potential markets, explore business models and help identify opportunities that could become viable technology companies.",
          "The objective isn't simply to brainstorm startup ideas. It's to find a problem worth solving that you are uniquely positioned and motivated to pursue.",
        ],
      },
      {
        heading: "Already Have an Idea? Even Better.",
        paragraphs: [
          "We'll help challenge it, validate the opportunity, define the business model and determine what actually needs to be built before investing significant time or money into development. If the opportunity makes sense, we'll work alongside you to turn it into a real product and company.",
        ],
      },
      {
        heading: "What We Build Together",
        paragraphs: ["Depending on where you're starting, Audax can support you through:"],
        items: [
          "Founder and opportunity discovery",
          "Startup idea generation and evaluation",
          "Market and customer validation",
          "Business model development",
          "Business planning and financial modelling",
          "Technology strategy and product roadmapping",
          "UX/UI and product design",
          "MVP scoping and software development",
          "AI strategy and implementation where applicable",
          "Go-to-market and launch strategy",
          "Early customer acquisition",
          "Preparing for investment and future growth",
        ],
        outro: [
          "Most importantly, we don't hand you a playbook and send you away to build it yourself. Under this program, Audax will actually build your MVP and help you launch the product in the market.",
        ],
      },
      {
        heading: "Who We're Looking For",
        paragraphs: ["We're looking for people who genuinely want to become entrepreneurs.", "You may be:"],
        items: [
          "A business professional who's always wanted to start something",
          "An industry expert who sees problems technology could solve",
          "A salesperson or operator who understands customers but doesn't know how to code",
          "Someone with a startup idea but no technical co-founder",
          "An aspiring entrepreneur still searching for the right opportunity",
        ],
        outro: [
          "You don't need to know how to code. You don't need to have founded a company before. You don't even need to have the idea yet.",
          "What matters is that you're ambitious, commercially minded, willing to learn and prepared to put real effort into building a company.",
        ],
      },
      {
        heading: "This Isn't a Job",
        paragraphs: [
          "The Audax Founder Program is not an employment opportunity.",
          "You aren't applying to work for Audax.",
          "You're applying for the opportunity to build a company of your own with Audax helping you get there.",
          "Founders accepted into the program will be expected to make a modest financial investment toward building and launching their venture. Audax contributes its technology, software development, AI, product and business-building capabilities alongside that investment.",
          "The exact structure and scope of each venture will depend on the founder, opportunity and technology required.",
        ],
      },
      {
        heading: "Why Build With Audax?",
        paragraphs: [
          "Starting a technology company can be difficult when you aren't technical.",
          "Finding a technical co-founder is hard. Hiring an entire development team is expensive. Raising investment before you've built anything can be even harder.",
          "We want to create another path.",
          "Audax gives selected founders access to the capabilities normally required to take a technology company from an idea on a whiteboard to a product in the hands of customers.",
          "You become the founder. Audax becomes the team helping you build it.",
        ],
      },
      {
        heading: "We're Selecting a Small Number of Founders",
        paragraphs: [
          "This program is intentionally selective.",
          "We're looking for people with the drive and potential to build meaningful companies, whether they already have the idea or need help discovering it.",
          "Acceptance isn't based on having the perfect pitch deck or startup résumé.",
          "We're looking at the person behind the application.",
        ],
      },
    ],
    closing: [
      "If you've always thought \"I'd love to start a company someday\", this may be the opportunity to stop waiting for someday.",
      "Apply to the Audax Founder Program and tell us why you want to become an entrepreneur.",
    ],
    questions: [],
  },
];

export function getCareerBySlug(slug: string): CareerJob | undefined {
  return careersData.find((c) => c.slug === slug);
}

export function getAllCareerSlugs(): string[] {
  return careersData.map((c) => c.slug);
}
