export interface CareerJob {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  intro: string[];
  ownership: {
    intro: string;
    items: string[];
    outro: string;
  };
  opportunity: {
    intro: string[];
    compIntro: string;
    compItems: string[];
    outro: string;
  };
  whoWereLookingFor: {
    intro: string;
    items: string[];
    outro: string[];
  };
  closing: string[];
  questions: string[];
}

export const careersData: CareerJob[] = [
  {
    slug: "founding-operator-entrepreneur-in-residence-verclara",
    title: "Founding Operator / Entrepreneur-in-Residence — Verclara",
    metaTitle: "Careers — Founding Operator / Entrepreneur-in-Residence | Audax Ventures",
    metaDescription:
      "Audax Ventures is looking for a Founding Operator / EIR to take ownership of Verclara's growth, with compensation tied to equity and profits.",
    intro: [
      "Want to build a software company, but haven't found the right idea yet?",
      "We may have an opportunity for you.",
      "At Audax Ventures, we've built and launched Verclara (www.verclara.io), a CRM and business operating system designed specifically for service-based businesses, consultants, fractional executives and small teams.",
      "The product is built. The technology is in place. The brand is launched.",
      "Now we're looking for the right entrepreneur to help turn Verclara into a growing SaaS company. We're looking for a Founding Operator / Entrepreneur-in-Residence who wants to take ownership of Verclara's growth and eventually have the opportunity to lead the business.",
      "This is not a traditional salaried position. It's an opportunity for someone who wants to become an entrepreneur and build meaningful ownership in a company without having to start from a blank page.",
    ],
    ownership: {
      intro: "You'll take the lead on the commercial growth of Verclara, including:",
      items: [
        "Customer acquisition and sales",
        "Marketing and go-to-market strategy",
        "Partnerships and distribution",
        "Customer onboarding and retention",
        "Gathering customer feedback and helping shape the product roadmap",
        "Testing new growth channels and opportunities",
        "Building the processes required to scale the business",
      ],
      outro:
        "You won't be doing it alone. Audax will continue to provide the software development, technical infrastructure and strategic support behind the platform.",
    },
    opportunity: {
      intro: [
        "There is no traditional salary at the outset. Instead, we want the person running Verclara to think and operate like an owner.",
      ],
      compIntro: "The compensation structure will include:",
      compItems: [
        "Meaningful equity in Verclara that vests over time",
        "Additional equity tied to achieving major growth milestones",
        "A percentage of monthly profits generated by Verclara",
        "A pathway toward salaried compensation as the business reaches defined revenue milestones",
        "The opportunity to ultimately become the long-term leader of Verclara",
      ],
      outro: "The better Verclara performs, the more valuable this opportunity becomes for you.",
    },
    whoWereLookingFor: {
      intro: "You might be a great fit if you:",
      items: [
        "Have always wanted to build a company of your own",
        "Are excited by startups, SaaS and entrepreneurship",
        "Are comfortable selling and talking to customers",
        "Can operate independently without waiting for someone to tell you what to do",
        "Are willing to experiment, fail quickly and keep moving",
        "Care more about ownership and long-term upside than having a conventional job",
        "Want to take something that already exists and make it significantly bigger",
      ],
      outro: [
        "You do not need to have founded a company before. We care much more about your drive, commercial instincts, creativity and ability to execute than the number of years on your resume.",
        "If your goal is simply to find another job, this probably isn't the right opportunity.",
        "But if you've been waiting for the right opportunity to become an entrepreneur, this might be it.",
      ],
    },
    closing: [
      "Interested? Apply today and include a cover letter that tells us a little about yourself, why entrepreneurship interests you, and what you would do in your first 90 days to grow Verclara.",
      "We want to find someone with strong entrepreneurial mindset qualities that is ready to work hard and build an innovative SaaS company.",
      "Bonus points if you submit a video of yourself talking as your cover letter!",
    ],
    questions: [
      "Do you have any previous entrepreneurship experience? (don't worry, this isn't a requirement!)",
      "Are you willing and/or able to invest any money into the company? (don't worry, this isn't a requirement!)",
      "Do you understand and accept that this opportunity does not include a guaranteed salary at the outset, with compensation instead structured around equity ownership and a share of profits?",
      "Are you looking for an entrepreneurial opportunity where your compensation and long-term upside are directly tied to the growth and performance of the business?",
      "Are you comfortable taking primary ownership of Verclara's sales, marketing, customer acquisition and overall business growth?",
    ],
  },
];

export function getCareerBySlug(slug: string): CareerJob | undefined {
  return careersData.find((c) => c.slug === slug);
}

export function getAllCareerSlugs(): string[] {
  return careersData.map((c) => c.slug);
}
